package App::Catable::Model::BlogDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'App::Catable::Schema',
);

=begin BlockComment

    Removing because it messes up the tests and over-rides the settings
    in $ENV{CATALYST_CONFIG} .

    connect_info => {
        dsn => 'dbi:SQLite:catable.db',
        user => '',
        password => '',
    }

=end BlockComment

=cut

=head1 NAME

App::Catable::Model::BlogDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<App::Catable>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<App::Catable::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.25

=head1 AUTHOR

Shlomi Fish, L<http://www.shlomifish.org/> .

=head1 LICENSE

This library is available under the terms of the MIT/X11 Licence.


=cut

1;
